### ISSUE TITLE
`No module named 'fontFeatures.pathUtils'`

### ISSUE THREAD

**Issue by JWesorick** [googlefonts/Gulzar#117]
After cloning the repo, installing the requirements and running `make` I get `No module named 'fontFeatures.pathUtils'`. It looks like pathUtils was removed from that package. Should the requirements be locked down more to specific versions?

**Comment by JWesorick** [comment]
I was able to change my `requirements.txt` to this to get it running:

```
git+https://github.com/simoncozens/karakul@882519f82efd829df2dae83b7f2410c00337fdd5
glyphsLib
uharfbuzz>=0.31.0
kurbopy>=0.8.21
fontmake
youseedee
tqdm
fontbakery==0.8.11a8
font-v
gftools
fontFeatures==1.7.4
```

but now after the progress bar reaching 100% get a new error:

```bash
Traceback (most recent call last):
  File "/Users/me/src/Gulzar/venv/bin/fez2fea", line 44, in <module>
    print(p.fontfeatures.asFea(do_gdef=args.do_gdef))
  File "/Users/me/src/Gulzar/venv/lib/python3.10/site-packages/fontFeatures/feaLib/FontFeatures.py", line 21, in asFea
    return self.asFeaAST(**kwargs).asFea()
  File "/Users/me/src/Gulzar/venv/lib/python3.10/site-packages/fontFeatures/feaLib/FontFeatures.py", line 149, in asFeaAST
    pre = k.feaPreamble(self)
  File "/Users/me/src/Gulzar/venv/lib/python3.10/site-packages/fontFeatures/feaLib/Routine.py", line 35, in feaPreamble
    if self.flags & 0xFF00:
TypeError: unsupported operand type(s) for &: 'dict' and 'int'
```

**Comment by YusukeShirakihara** [comment]
@simoncozens  or @JWesorick 
I attempted the make command using the same configuration, and encountered a similar error (with fontFeatures==1.7.3 set). So, I would be grateful if you could provide any guidance on resolving this issue. Do you have any update?
